FIAP_TDD/Models/Aluno.cs
namespace FIAP_TDD.Models
{
    public class Aluno
    {
    }
}

FIAP_TDD/Models/ErrorViewModel.cs
namespace FIAP_TDD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FIAP_TDD/Controllers/AlunoController.cs
using FIAP_TDD.Data.Models;
using FIAP_TDD.Services;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;

namespace FIAP_TDD.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoService _aluno;

        public AlunoController(IAlunoService aluno)
        {
            _aluno = aluno;
        }
        public async Task<IActionResult> Index()
        {
            var alunos = await _aluno.BuscarTodos();
            return View(alunos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(AlunoModel aluno)
        {
            if (await _aluno.GravarAluno(aluno))
            {
                return RedirectToAction(nameof(Index));

            }
            return View(aluno);
        }

        public async Task<IActionResult> Editar(int id)
        {
            var aluno = await _aluno.BuscarPorId(id);
            return View(aluno);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(AlunoModel aluno)
        {
            if (await _aluno.EditarAluno(aluno))
            {
                return RedirectToAction(nameof(Index));

            }
            return View(aluno);
        }

        [HttpPost]
        public async Task<bool> Deletar(int id)
        {
            if (id != 0)
            {
                return await _aluno.Deletar(id);

            }
            return false;
        }
        
    }
}

FIAP_TDD/Controllers/HomeController.cs
using FIAP_TDD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FIAP_TDD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FIAP_TDD/Controllers/TurmaController.cs
using FIAP_TDD.Data.Models;
using FIAP_TDD.Services;
using Microsoft.AspNetCore.Mvc;

namespace FIAP_TDD.Controllers
{
    public class TurmaController : Controller
    {
        private readonly ITurmaService _turma;

        public TurmaController(ITurmaService turma)
        {
            _turma = turma;
        }

        public async Task<IActionResult> Index()
        {
            var turmas = await _turma.BuscarTodas();
            return View(turmas);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Criar(TurmaModel turmaModel)
        {
            if (await _turma.Gravar(turmaModel))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(turmaModel);
        }

        public async Task<IActionResult> Editar(int? id)
        {
            if (id != null)
            {
                TurmaModel? turma = await _turma.BuscarPorId(id.Value);
                if (turma == null) return RedirectToAction(nameof(Index));
                return View(turma);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Editar(TurmaModel turmaModel)
        {
            if (await _turma.Editar(turmaModel))
            {
                return RedirectToAction(nameof(Index));
            }
            return View(turmaModel);
        }

        [HttpPost]
        public async Task<bool> Deletar(int? id)
        {
            if (id != null)
            {
                try
                {
                    await _turma.Deletar(id.Value);
                    return true;
                }
                catch (Exception)
                {
                    return false;                 
                }
            }
            return false;
        }
    }
}

FIAP_TDD/Views/Aluno/Criar.cshtml
@model AlunoModel

<div>
    <h2>Criar Aluno</h2>
</div>

<form asp-action="Criar" method="post">
    <div class="form-group mt-2">
        <label asp-for="Nome"></label>
        <input class="form-control" asp-for="Nome" placeholder="Nome">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Usuario"></label>
        <input class="form-control" asp-for="Usuario" placeholder="Usuario">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Senha"></label>
        <input class="form-control" asp-for="Senha" placeholder="Usuario">
    </div>
    <div class="mt-2">
        <input type="submit" class="btn btn-primary" value="Criar" />
    </div>
</form>

FIAP_TDD/Views/Aluno/Editar.cshtml
@model AlunoModel

<div>
    <h2>Editar Aluno</h2>
</div>

<form asp-action="Editar" method="post">
    <div class="form-group mt-2">
        <label asp-for="Nome"></label>
        <input class="form-control" asp-for="Nome" placeholder="Nome">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Usuario"></label>
        <input class="form-control" asp-for="Usuario" placeholder="Usuario">
    </div>
    <div class="mt-2">
        <input type="submit" class="btn btn-primary" value="Editar" />
    </div>
</form>

FIAP_TDD/Views/Aluno/Index.cshtml
@using FIAP_TDD.Data.Models;
@model IEnumerable<AlunoModel>

<div class="container">
    <h2>Alunos</h2>
    <a asp-action="Criar" class="btn btn-primary">Criar Aluno</a>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Usuario</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td></td>
                <td>@item.Nome</td>
                <td>@item.Usuario</td>
                <td>

                    <div class="btn-group">
                        <button type="button" data-bs-toggle="dropdown" class="btn btn-danger">Acões</button>
                        <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="Editar" asp-route-id="@item.Id">Editar</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><button class="dropdown-item" onclick="DeletarAluno(@item.Id)">Deletar</button></li>
                        </ul>
                    </div>

                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        function DeletarAluno(id){
            var data = {id:id}
            $.ajax({
                method:"POST",
                url:"/Aluno/Deletar",
                data:data,
                success:(retorno)=>{
                    if (retorno == true) {
                        alert("Aluno deletado com sucesso")
                        location.reload()
                    }
                    else {
                        console.log(retorno)
                        alert("Erro ao deletar o Aluno")
                    }
                }
            });
        }
    </script>
}

FIAP_TDD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FIAP_TDD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FIAP_TDD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FIAP_TDD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FIAP_TDD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turma" asp-action="Index">Turma</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FIAP_TDD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FIAP_TDD/Views/Turma/Criar.cshtml
@model TurmaModel

<h2>Criar Turma</h2>

<form method="post" asp-action="Criar">
    <div class="form-group mt-2">
        <label asp-for="Turma"></label>
        <input class="form-control" asp-for="Turma" placeholder="Nome">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Ano"></label>
        <input class="form-control" asp-for="Ano" placeholder="Nome">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Curso_Id"></label>
        <input class="form-control" asp-for="Curso_Id" placeholder="Nome">
    </div>
    <input type="submit" class="btn btn-primary" value="Criar" />
</form>

FIAP_TDD/Views/Turma/Editar.cshtml
@model TurmaModel

<h2>Criar Turma</h2>

<form method="post" asp-action="Editar">
    <div class="form-group mt-2">
        <label asp-for="Turma"></label>
        <input class="form-control" asp-for="Turma" placeholder="Nome">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Ano"></label>
        <input class="form-control" asp-for="Ano" placeholder="Nome">
    </div>
    <div class="form-group mt-2">
        <label asp-for="Curso_Id"></label>
        <input class="form-control" asp-for="Curso_Id" placeholder="Nome">
    </div>
    <input type="submit" class="btn btn-primary" value="Editar" />
</form>

FIAP_TDD/Views/Turma/Index.cshtml
@model IEnumerable<TurmaModel>

<div>
    <h2>Lista De Turmas</h2>
    <a class="btn btn-primary" asp-action="Criar">Criar Turma Nova</a>
</div>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Curso Id</th>
            <th scope="col">Nome</th>
            <th scope="col">Ano</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var turma in Model)
        {
            <tr>
                <td></td>
                <td>@turma.Curso_Id</td>
                <td>@turma.Turma</td>
                <td>@turma.Ano</td>
                <td>
                    <div class="btn-group">
                        <button type="button" data-bs-toggle="dropdown" class="btn btn-danger">Acões</button>
                        <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="Editar" asp-route-id="@turma.Id">Editar</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><button class="dropdown-item" onclick="DeletarTurma(@turma.Id)">Deletar</button></li>
                        </ul>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>



@section Scripts{
    <script>
        function DeletarTurma(id) {
            var data = { id: id }
            $.ajax({
                method: "POST",
                url: "/Turma/Deletar",
                data: data,
                success: (retorno) => {
                    if (retorno == true) {
                        alert("Turma deletada com sucesso")
                        location.reload()
                    }
                    else {
                        console.log(retorno)
                        alert("Erro ao deletar a Turma")
                    }
                }
            });
        }
    </script>
}